sudo: false

language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install coveralls
  - pip install codecov

script:
  - find ./mapreduce -name \*.py -exec pycodestyle --ignore=E111 {} +
  - coverage run tests.py

after_success:
  - coveralls
  - codecov

notifications:
  email: false
