sudo: false

language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - find ./mapreduce -name \*.py -exec pycodestyle --ignore=E111 {} +
  - python -m coverage run ./tests/tests.py

after_success:
  - pip install codecov
  - codecov -t fd779b81-85b4-45a8-ba5f-5d500c7398cf
  - pip install coveralls
  - coveralls

notifications:
  email: false
