language: python
python:
    - "2.7"
sudo: required
install:
    - pip install -r requirements.txt
    - pip install pycodestyle
    - pip install coveralls
    - pip install codecov
    - python setup.py install
script:
    - find ./mapreduce -name \*.py -exec pycodestyle {} +
after_success:
    - coveralls
    - codecov
notifications:
    email: false